[catalogue]
items = coffee_cup, coin, notebook, pencil, handkerchief, key, fallen_clock, stick

[inventory.coffee_cup]
graphic = inventory.coffee_cup
label = coffee cup
script = coffee_cup.ana

[inventory.coin]
graphic = inventory.coin
label = coin
script = coin.ana

[inventory.notebook]
graphic = inventory.notebook
label = notebook
script = notebook.ana

[inventory.pencil]
graphic = inventory.pencil
label = pencil
script = pencil.ana

[inventory.handkerchief]
graphic = inventory.handkerchief
label = handkerchief
script = handkerchief.ana

[inventory.key]
graphic = inventory.key
label = key
script = key.ana

[inventory.fallen_clock]
graphic = inventory.fallen_clock
label = fallen clock
script = fallen_clock.ana

[inventory.stick]
graphic = inventory.stick
label = stick
script = stick.ana
